In [11]:
#ndarry的索引(index),切割(slice)

import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]


array([7, 8, 9])

In [12]:
import random
random.randint(50,100)

90

In [13]:
np.random.randint(50, 101, size=5) # 生成一个包含50个随机整数的数组，范围从50到100
# 生成一个包含50个随机整数的数组，范围从50到100
scores = np.random.randint(50,101, size=(50, 5)) # 生成一个包含50个随机整数的二维数组，范围从50到100
scores.size # scores.shape 返回一个元组，表示数组的维度
scores.shape # scores.shape[0] 返回数组的行数

(50, 5)

In [14]:
scores[:,0] # 取出所有行的第一列
scores[:,0:1] # 取出所有行的第一列，返回二维数组

array([[ 76],
       [ 77],
       [ 86],
       [ 84],
       [ 69],
       [ 73],
       [ 65],
       [ 78],
       [ 58],
       [ 50],
       [ 71],
       [ 54],
       [ 62],
       [ 77],
       [ 50],
       [ 94],
       [ 94],
       [ 71],
       [ 87],
       [ 62],
       [ 96],
       [ 79],
       [ 87],
       [ 52],
       [ 91],
       [100],
       [ 67],
       [ 88],
       [ 94],
       [ 54],
       [ 72],
       [ 94],
       [ 76],
       [ 81],
       [ 95],
       [ 74],
       [ 53],
       [ 67],
       [ 68],
       [ 89],
       [ 78],
       [ 88],
       [ 69],
       [ 61],
       [ 62],
       [ 71],
       [ 98],
       [ 53],
       [ 55],
       [ 75]], dtype=int32)

In [15]:

scores[0,:]
scores[0:1,:]

array([[76, 68, 55, 96, 55]], dtype=int32)

In [16]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([70. , 71.6, 83. , 82.2, 81.8, 70.4, 81. , 79. , 70.8, 57.2, 63.2,
       69. , 66.8, 76.6, 63.4, 73.6, 70. , 68.4, 70.4, 65.6, 72.6, 69.4,
       78.6, 76. , 76.2, 72.2, 72.6, 73.6, 71.6, 64.2, 72.2, 79.8, 71.6,
       72.6, 82.4, 83.8, 71.4, 69.8, 76.8, 84. , 67.8, 75.2, 64.8, 66.8,
       79.8, 70.6, 90.4, 64.8, 68.8, 76. ])

In [ ]:
#使用比較運算子
arr = np.random.randn(5) # 生成一个包含5个随机数的数组
arr > 0 # 返回一个布尔数组，表示每个元素是否大于0 

array([False,  True,  True, False, False])

In [18]:

np.where(arr > 0, 1, 0)

array([0, 1, 0, 1, 0])

In [19]:
np.where(arr > 0, 1, arr)

array([-0.32013813,  1.        , -0.54205078,  1.        , -0.41067975])