## https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [2]:
import numpy as np
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [3]:

np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [6]:

np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.random.rand(3, 4)

array([[0.94989958, 0.25269511, 0.03118008, 0.69835093],
       [0.35765138, 0.34214813, 0.06498686, 0.53882941],
       [0.45609019, 0.2665919 , 0.22631041, 0.71277326]])

In [8]:
scores = np.random.randint(50,101,size=(50, 5))