https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

In [1]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[63, 69, 84, 56, 68],
       [60, 83, 76, 65, 59],
       [62, 52, 75, 95, 96],
       [88, 77, 83, 59, 72],
       [73, 69, 99, 51, 51]], dtype=int32)

In [2]:
scores[:3,2:]

array([[84, 56, 68],
       [76, 65, 59],
       [75, 95, 96]], dtype=int32)

In [3]:
scores[4]
scores[4,:]
scores[4:,:]

array([[73, 69, 99, 51, 51]], dtype=int32)

In [4]:
scores[:,:2]

array([[63, 69],
       [60, 83],
       [62, 52],
       [88, 77],
       [73, 69]], dtype=int32)