https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

In [ ]:
# numpy的索引和切割
# 1. 创建一个5x5的二维数组，元素为50到100之间的随机整数
# 2. 打印出这个数组
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[73, 89, 58, 53, 54],
       [53, 88, 59, 76, 69],
       [76, 92, 59, 65, 54],
       [72, 94, 81, 93, 90],
       [63, 88, 89, 65, 70]], dtype=int32)

In [6]:
scores[:3,2:]

array([[58, 53, 54],
       [59, 76, 69],
       [59, 65, 54]], dtype=int32)

In [7]:
scores[4]
scores[4,:]
scores[4:,:]

array([[63, 88, 89, 65, 70]], dtype=int32)

In [8]:
scores[:,:2]

array([[73, 89],
       [53, 88],
       [76, 92],
       [72, 94],
       [63, 88]], dtype=int32)

In [ ]:
#numpy的統計工具

scores = np.random.randint(50,101,size=(5,5))
scores

In [ ]:

scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

In [ ]:

#加總
np.sum(scores,axis=1)

In [ ]:
#平均
np.mean(scores, axis=1)

In [ ]:

#最大
np.max(scores,axis=1)

In [ ]:

#最小
np.min(scores,axis=1)

In [ ]:

#中間數
np.median(scores,axis=1)

In [ ]:
#標準差
np.std(scores,axis=1)